version: '3'
services:
  drupal:
    build: ./docker
    volumes:
      - ./docker/drupal:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/html
    ports:
      - "8000:80"
